import re
from typing import Final

from prometheus_client import CONTENT_TYPE_LATEST, Counter, Histogram, generate_latest
from starlette.requests import Request

UUID_PATTERN: Final[re.Pattern[str]] = re.compile(
    r"\b[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}\b"
)
NUMERIC_SEGMENT_PATTERN: Final[re.Pattern[str]] = re.compile(r"/\d+")

http_requests_total = Counter(
    "barcodezen_http_requests_total",
    "Total HTTP requests handled by the API middleware.",
    ["method", "path", "status_code", "outcome"],
)

http_request_duration_ms = Histogram(
    "barcodezen_http_request_duration_ms",
    "HTTP request latency in milliseconds.",
    ["method", "path"],
    buckets=(5, 10, 25, 50, 100, 250, 500, 1000, 2500, 5000),
)

auth_rejections_total = Counter(
    "barcodezen_auth_rejections_total",
    "Total authorization/authentication rejections generated by middleware.",
    ["error_code"],
)

db_ready_checks_total = Counter(
    "barcodezen_db_ready_checks_total",
    "Total readiness checks against the database.",
    ["status"],
)

db_ready_check_duration_ms = Histogram(
    "barcodezen_db_ready_check_duration_ms",
    "Database readiness check duration in milliseconds.",
    ["status"],
    buckets=(1, 2.5, 5, 10, 25, 50, 100, 250, 500, 1000),
)


def normalize_metrics_path(path: str) -> str:
    path_with_uuid_placeholder = UUID_PATTERN.sub("{id}", path)
    normalized = NUMERIC_SEGMENT_PATTERN.sub("/{id}", path_with_uuid_placeholder)
    return normalized


def resolve_metrics_path(request: Request) -> str:
    route = request.scope.get("route")
    route_path = getattr(route, "path", None)
    if isinstance(route_path, str):
        return route_path
    return normalize_metrics_path(request.url.path)


def observe_http_request(
    *,
    method: str,
    path: str,
    status_code: int,
    duration_ms: float,
    outcome: str,
) -> None:
    http_requests_total.labels(
        method=method.upper(),
        path=path,
        status_code=str(status_code),
        outcome=outcome,
    ).inc()
    http_request_duration_ms.labels(
        method=method.upper(),
        path=path,
    ).observe(max(duration_ms, 0.0))


def observe_auth_rejection(*, error_code: str) -> None:
    auth_rejections_total.labels(error_code=error_code).inc()


def observe_db_ready_check(*, status: str, duration_ms: float) -> None:
    db_ready_checks_total.labels(status=status).inc()
    db_ready_check_duration_ms.labels(status=status).observe(max(duration_ms, 0.0))


def render_metrics() -> bytes:
    return generate_latest()


METRICS_CONTENT_TYPE = CONTENT_TYPE_LATEST
